server:
  port: 8888

spring:
  application:
    name: objectionDetectionComputer
  redis:
    #数据库索引
    host: 127.0.0.1
    port: 16379
    Auth: a19980427
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
      timeout: 10000

pythonconfig:
  anacondaPrefix: D:\anaconda\envs\mmcv\python
  execPrefix: D:\MyPaper\deep-learning-for-image-processing\pytorch_object_detection\retinaNet\predict.py

